### ISSUE TITLE
server panic when running /disconnect

### ISSUE THREAD

**Issue by AaronM04** [conwayste/netwayste#8]
I joined a room with the client, did a /list, then did a /disconnect, which caused the server to crash:

```
Fri 2019-01-18 21:44:57.901163 [TRACE] - [Request] cookie: Some("1A0dJleB68pPuRIyCNVDlQ==") sequence: 11 resp_ack: Some(11) event: Disconnect
Fri 2019-01-18 21:44:57.901601 [TRACE] - [CAN PROCESS?] Ack: 10 Sqn: 11
Fri 2019-01-18 21:44:57.901869 [TRACE] - [PROCESS IMMEDIATE]
thread 'main' panicked at 'Player not found for PlayerID(4162779497) while handling request action Disconnect', src/server.rs:927:25
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:476
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:345
   7: server::ServerState::handle_request_action
             at src/server.rs:927
   8: server::ServerState::process_player_request_action
             at src/server.rs:627
   9: server::ServerState::decode_packet
             at src/server.rs:861
  10: server::main::{{closure}}
             at src/server.rs:1207
  11: <futures::stream::fold::Fold<S, F, Fut, T> as futures::future::Future>::poll
             at /home/x/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/stream/fold.rs:58
  12: <futures::future::map::Map<A, F> as futures::future::Future>::poll
             at /home/x/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/map.rs:30
  13: <futures::future::map_err::MapErr<A, F> as futures::future::Future>::poll
             at /home/x/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/map_err.rs:30
  14: <futures::future::map::Map<A, F> as futures::future::Future>::poll
             at /home/x/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/map.rs:30
  15: <futures::future::select::Select<A, B> as futures::future::Future>::poll
             at /home/x/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/select.rs:48
  16: <futures::future::map::Map<A, F> as futures::future::Future>::poll
             at /home/x/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/map.rs:30
  17: <futures::task_impl::Spawn<T>>::poll_future_notify::{{closure}}
             at /home/x/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/task_impl/mod.rs:288
  18: <futures::task_impl::Spawn<T>>::enter::{{closure}}
             at /home/x/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/task_impl/mod.rs:362
  19: futures::task_impl::std::set
             at /home/x/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/task_impl/std/mod.rs:78
  20: <futures::task_impl::Spawn<T>>::enter
             at /home/x/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/task_impl/mod.rs:362
  21: <futures::task_impl::Spawn<T>>::poll_future_notify
             at /home/x/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/task_impl/mod.rs:288
  22: tokio_core::reactor::Core::run::{{closure}}
             at /home/x/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.12/src/reactor/mod.rs:235
  23: <scoped_tls::ScopedKey<T>>::set
             at /home/x/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-0.1.0/src/lib.rs:135
  24: tokio_core::reactor::Core::run
             at /home/x/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.12/src/reactor/mod.rs:234
  25: server::main
             at src/server.rs:1284
  26: std::rt::lang_start::{{closure}}
             at libstd/rt.rs:74
  27: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  28: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  29: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  30: std::rt::lang_start
             at libstd/rt.rs:74
  31: main
  32: __libc_start_main
  33: _start
```

I'm on the reliability_part3 branch (commit 864bf51).

**Comment by Manghi** [comment]
Merged via  8fb871f .
